### ISSUE TITLE
Relay mutation builder + errors plugin

### ISSUE THREAD

**Issue by jamiehodge** [hayes/giraphql#182]
First of all, I'd like to say how happy I/we are with giraphql. It's been a large step up from using nexus, both because of the lack of extra build step, but also because the errors are generally much easier to understand and resolve. Thank you for the hard work.

I recently started using the errors plugin together with the relay mutation builder. The later creates the input and payload pattern, while the former creates the `FooSuccess | MyError` pattern. When combined with the relay builder, you end up with `FooSuccess { payload: FooPayload }`. I'm just wondering out loud whether this extra indirection is necessary. I guess the real issue here is that you have two competing patterns and the Success type supersedes the Payload type. Any thoughts?

I see that you have a with-input PR sitting in the dock. I wonder if that's a better fit with the errors plugin.

**Comment by hayes** [comment]
The reason the error plugin creates an extra wrapper to put in the union is because fields may be list fields.   This obviously wouldn't be the case for a mutation payload.  I think an option that could work would be to have an extra option for non-list fields that disables wrapping. 

I'm not sure if it makes sense to enable it by default or not for relay mutations.   Could probably have some builder level settings for that

**Comment by hayes** [comment]
I am adding a `directResult` option you can pass in the `errors` object on a field that will allow you to not generate an intermediate result type.  Setting this to true for your relay mutation fields should work
