### ISSUE TITLE
Expose enum ref's values

### ISSUE THREAD

**Issue by Jomik** [hayes/giraphql#266]
I think it would be nice to be able to access the values of an `EnumRef` at runtime.
Currently I am defining my enums as a TypeScript enum, then I can use a type guard like below.
```ts
export const isValueInEnum = <T extends Record<string, string>>(
  obj: T,
  value: any
): value is T[keyof T] => Object.values(obj).includes(value);
```
Would be nice to just use the enum ref, as I am not too fond of the TypeScript enums and do not need it.

**Comment by hayes** [comment]
This would somewhat go against some of the core principles of refs.  Refs are inteded to be references to types that may not be fully defined, allowing for recursive, or partial definitions.  In the case of enums I don't see obvious downsides.  It might be better to create a helper that does this for you.

You can access the values via something like: `builder.configStore.getConfig(ref, 'Enum').giraphqlOptions.values`.  How to parse out the values will depend on how you define your enum.

Refs currently don't have the context to be able to resolve this themselves, since they don't store a reference to the builder.  If this were to be implemented in core, there would need to be a new ResovlerEnumRef class or something that has a reference to the builder, that could then resolve the config through the builder, but I am hesitant to introduce that type of a change, because I would likely need to mirror it for other types of refs to keep things consistent, and that would raise other more complicated issues.

**Comment by Jomik** [comment]
Ohh that makes complete sense. And completely agree that it shouldn't exist in core.
Not too fond of that helper either, I guess it would be better to simply extract my values definition to its own variable and export that. 💪
