### ISSUE TITLE
Export zod validator creation functions

### ISSUE THREAD

**Issue by kesne** [hayes/giraphql#43]
It would be super useful to be able to re-use the same zod schema on the frontend and in graphQL. It seems like the best way to do this would be to export functions from the validation plugin which you can pass in the validation rules, and it would spit out a zod schema. For example...

```ts
const badPassword = createZodSchema({ minLength: 4, maxLength: 8 });
```

This would then allow us to do something like this:

```ts
// Shared.ts:
export const PasswordValidation = { minLength: 4, maxLength: 8 };

// Server.js
t.arg.string({ validate: PasswordValidation });

// Client.js
useForm({
  schema: zod.object({
    password: createZodSchema(PasswordValidation)
  })
})
```

**Comment by hayes** [comment]
released in `@giraphql/plugin-validation@1.2.0`

docs: https://giraphql.com/plugins/validation#sharing-schemas-with-client-code

**Comment by hayes** [comment]
Realizing I just gave you what you asked for instead of what you actually wanted.  Going to re-open this. 

What I actually should do here is just allow passing in your own zod validator into the validation option.  Then you can define your validator once and re-use it.  It doesn't work well as the default (or only) option, but allowing a schema to be passed in seems pretty straight forward.

**Comment by hayes** [comment]
okay, better solution is implemented now.

you can pass something like `validate: { schema: zod.string().max(5) }` now, making it easier to re-use existing zod schemas without using the weird alternate syntax from this plugin.

**Comment by mmahalwy** [comment]
oh hai @kesne 👋
