### ISSUE TITLE
Add Mutations to Relay Plugin

### ISSUE THREAD

**Issue by litewarp** [hayes/giraphql#70]
Another feature request. Would it be possible to add a mutation type that is relay compatible? That is, it follows the [Relay Specification for Mutations](https://relay.dev/docs/v1.6.2/graphql-server-specification/#mutations).

The relay-graphql library has a [helper for this](https://github.com/graphql/graphql-relay-js#mutations) and there's a [nexus plugin](https://www.npmjs.com/package/@jcm/nexus-plugin-relay-mutation) that does something similar. 

Thanks again. I'm digging this system.

**Comment by hayes** [comment]
Yup, I think I can add that.

Would probably look something like:

```ts
t.relayMutation({
  fields: inputFields,
  ... otherOptionsForInputType
}, {
  resolve,
  ...otherOptionsForResolve,
}, {
  fields: payloadFields,
  ...otherOptionsForPayloadType
})
```
Which is a bit dense/verbose.   I'll think a bit more on if there is a cleaner way to do this, but one of GiraphQLs features is to allow required fields to be added to any options object.  This means we need to expose an options object for all 3 pieces (the input object, the mutation field, and the payload object).  This is a little more complicated than the global connection fields, but should be doable relatively soon.

**Comment by litewarp** [comment]
Yeah, Relay is often dense/verbose, but it is what it is ... 

In the [reference implementation](https://github.com/graphql/graphql-relay-js#mutations), the mutation object has four properties. It would be great if we could keep the property names consistent.
 
```
const mutationType = ({
  name: '',
  inputFields: {},
  outputFields: {},
  mutateAndGetPayload: async (src, args, ctx, info) => {}
})
```

**Comment by hayes** [comment]
@litewarp PR for adding this feature is up (#73).  No docs yet, but you can look at the PR description (or source) for example usage, still need to add more tests.

Regarding matching options the relay reference implementation.  Using the same API won't work, but I've update the the options for defining fields to be inputFields and outputFields to help readability.  I am going to leave resolve as is rather than using mutateAndGetPayload. 


Let me know if this looks good to you.  If you have a chance to try out the preview versions, any feedback would be appreciated.

**Comment by litewarp** [comment]
Will pull the alpha packages and give them a try later today. You rock.

**Comment by hayes** [comment]
released
